### Post a new message to cohort chat
POST http://localhost:5082/api/cohorts/{{cohort_id}}/chat/messages
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "cohortId": "{{cohort_id}}",
  "userId": "{{user_id}}",
  "content": "Hello world!"
}