// <auto-generated />
using System;
using AlgoDuck.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlgoDuck.Migrations
{
    [DbContext(typeof(ApplicationCommandDbContext))]
    [Migration("20260123113915_UserAchievementsSafetyTightening")]
    partial class UserAchievementsSafetyTightening
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlgoDuck.Models.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("api_key_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("key_hash");

                    b.Property<string>("KeySalt")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("key_salt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("prefix");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("api_key_pk");

                    b.HasIndex("Prefix")
                        .HasDatabaseName("api_key_prefix_idx");

                    b.HasIndex("UserId");

                    b.ToTable("api_key", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<int>("AmountSolved")
                        .HasColumnType("integer")
                        .HasColumnName("amount_solved");

                    b.Property<Guid?>("CohortId")
                        .HasColumnType("uuid")
                        .HasColumnName("cohort_id");

                    b.Property<DateTime?>("CohortJoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cohort_joined_at");

                    b.Property<int>("Coins")
                        .HasColumnType("integer")
                        .HasColumnName("coins");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("Experience")
                        .HasColumnType("integer")
                        .HasColumnName("experience");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("application_user_pk");

                    b.HasIndex("CohortId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("application_user", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.AssistanceMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsUserMessage")
                        .HasColumnType("boolean")
                        .HasColumnName("is_user_message");

                    b.HasKey("MessageId");

                    b.HasIndex("ChatId");

                    b.ToTable("assistance_message", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.AssistantChat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("assistant_chat_id");

                    b.HasIndex("ProblemId");

                    b.HasIndex("UserId");

                    b.ToTable("assistant_chat", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.AssistantMessageFragment", b =>
                {
                    b.Property<Guid>("MessageFragmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("fragment_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("fragment_content");

                    b.Property<string>("FragmentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fragment_type");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.HasKey("MessageFragmentId");

                    b.HasIndex("MessageId");

                    b.ToTable("assistant_message_code_fragment", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("category_name");

                    b.HasKey("CategoryId")
                        .HasName("category_pk");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.CodeExecutionStatistics", b =>
                {
                    b.Property<Guid>("CodeExecutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("code_execution_statistics_id");

                    b.Property<long>("ExecutionEndNs")
                        .HasColumnType("bigint")
                        .HasColumnName("execution_end_ns");

                    b.Property<long>("ExecutionStartNs")
                        .HasColumnType("bigint")
                        .HasColumnName("execution_start_ns");

                    b.Property<byte>("ExecutionType")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<int>("ExitCode")
                        .HasColumnType("integer")
                        .HasColumnName("exit_code");

                    b.Property<long>("JvmPeakMemKb")
                        .HasColumnType("bigint")
                        .HasColumnName("jvm_peak_mem_kb");

                    b.Property<Guid?>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<byte>("Result")
                        .HasColumnType("smallint")
                        .HasColumnName("result");

                    b.Property<byte>("TestCaseResult")
                        .HasColumnType("smallint")
                        .HasColumnName("test_case_result");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("CodeExecutionId")
                        .HasName("code_execution_statistics_id");

                    b.HasIndex("ProblemId");

                    b.HasIndex("UserId");

                    b.ToTable("code_execution_statistics", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.Cohort", b =>
                {
                    b.Property<Guid>("CohortId")
                        .HasColumnType("uuid")
                        .HasColumnName("cohort_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("CreatedByUserLabel")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by_user_label");

                    b.Property<DateTime?>("EmptiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("emptied_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("join_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("CohortId")
                        .HasName("cohort_pk");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("JoinCode")
                        .IsUnique()
                        .HasDatabaseName("cohort_join_code_uq");

                    b.ToTable("cohort", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.Contest", b =>
                {
                    b.Property<Guid>("ContestId")
                        .HasColumnType("uuid")
                        .HasColumnName("contest_id");

                    b.Property<string>("ContestDescription")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("contest_description");

                    b.Property<DateTime>("ContestEndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("contest_end_date");

                    b.Property<string>("ContestName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("contest_name");

                    b.Property<DateTime>("ContestStartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("contest_start_date");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.HasKey("ContestId")
                        .HasName("contest_pk");

                    b.HasIndex("ItemId");

                    b.ToTable("contest", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.Difficulty", b =>
                {
                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uuid")
                        .HasColumnName("difficulty_id");

                    b.Property<string>("DifficultyName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("difficulty_name");

                    b.Property<decimal>("RewardScaler")
                        .HasColumnType("numeric")
                        .HasColumnName("reward_scaler");

                    b.HasKey("DifficultyId")
                        .HasName("difficulty_pk");

                    b.ToTable("difficulty", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.EditorLayout", b =>
                {
                    b.Property<Guid>("EditorLayoutId")
                        .HasColumnType("uuid")
                        .HasColumnName("editor_layout_id");

                    b.Property<bool>("IsDefaultLayout")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default_layout");

                    b.Property<string>("LayoutName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("layout_name");

                    b.HasKey("EditorLayoutId")
                        .HasName("editor_layout_pk");

                    b.ToTable("editor_layout", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.EditorTheme", b =>
                {
                    b.Property<Guid>("EditorThemeId")
                        .HasColumnType("uuid")
                        .HasColumnName("editor_theme_id");

                    b.Property<string>("ThemeName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("theme_name");

                    b.HasKey("EditorThemeId")
                        .HasName("editor_theme_pk");

                    b.ToTable("editor_theme", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.Item", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<int>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.Property<bool>("Purchasable")
                        .HasColumnType("boolean")
                        .HasColumnName("purchasable");

                    b.Property<Guid>("RarityId")
                        .HasColumnType("uuid")
                        .HasColumnName("rarity_id");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.HasKey("ItemId")
                        .HasName("shop_pk");

                    b.HasIndex("CreatedById");

                    b.HasIndex("RarityId");

                    b.ToTable("item", (string)null);

                    b.HasDiscriminator<string>("type").HasValue("Item");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AlgoDuck.Models.ItemOwnership", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchased_at");

                    b.Property<string>("ownership_type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("ItemId", "UserId")
                        .HasName("purchases_pk");

                    b.HasIndex("UserId");

                    b.ToTable("purchase", (string)null);

                    b.HasDiscriminator<string>("ownership_type").HasValue("ItemOwnership");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AlgoDuck.Models.Message", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<Guid>("CohortId")
                        .HasColumnType("uuid")
                        .HasColumnName("cohort_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("MediaContentType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("media_content_type");

                    b.Property<string>("MediaKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("media_key");

                    b.Property<int>("MediaType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("media_type");

                    b.Property<string>("Message1")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("message");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("MessageId")
                        .HasName("message_pk");

                    b.HasIndex("CohortId");

                    b.HasIndex("UserId");

                    b.ToTable("message", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.OwnsLayout", b =>
                {
                    b.Property<Guid>("LayoutId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("boolean")
                        .HasColumnName("is_selected");

                    b.HasKey("LayoutId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("owns_layout", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.Problem", b =>
                {
                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uuid")
                        .HasColumnName("difficulty_id");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ProblemTitle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("problem_title");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("ProblemId")
                        .HasName("problem_pk");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DifficultyId");

                    b.ToTable("problem", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.PurchasedTestCase", b =>
                {
                    b.Property<Guid>("TestCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_case_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("TestCaseId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("PurchasedTestCases");
                });

            modelBuilder.Entity("AlgoDuck.Models.Rarity", b =>
                {
                    b.Property<Guid>("RarityId")
                        .HasColumnType("uuid")
                        .HasColumnName("rarity_id");

                    b.Property<int>("RarityLevel")
                        .HasColumnType("integer")
                        .HasColumnName("rarity_level");

                    b.Property<string>("RarityName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("rarity_name");

                    b.HasKey("RarityId")
                        .HasName("rarity_pk");

                    b.ToTable("rarity", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("refresh_token_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("token_hash");

                    b.Property<string>("TokenPrefix")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_prefix");

                    b.Property<string>("TokenSalt")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("token_salt");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("refresh_token_pk");

                    b.HasIndex("ReplacedByTokenId");

                    b.HasIndex("SessionId");

                    b.HasIndex("TokenPrefix")
                        .HasDatabaseName("refresh_token_prefix_idx");

                    b.HasIndex("UserId");

                    b.ToTable("refresh_token", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.Session", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("refresh_token_hash");

                    b.Property<string>("RefreshTokenPrefix")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("refresh_token_prefix");

                    b.Property<string>("RefreshTokenSalt")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("refresh_token_salt");

                    b.Property<Guid?>("ReplacedBySessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_session_id");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("SessionId")
                        .HasName("session_pk");

                    b.HasIndex("RefreshTokenPrefix")
                        .HasDatabaseName("session_refresh_prefix_idx");

                    b.HasIndex("ReplacedBySessionId");

                    b.HasIndex("UserId");

                    b.ToTable("session", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.StudyReminder", b =>
                {
                    b.Property<int>("StudyReminderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("study_reminder_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudyReminderId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("code");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("name");

                    b.HasKey("StudyReminderId")
                        .HasName("study_reminder_pk");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("study_reminder_code_uq");

                    b.HasIndex("DayOfWeek")
                        .IsUnique()
                        .HasDatabaseName("study_reminder_day_of_week_uq");

                    b.ToTable("study_reminder", null, t =>
                        {
                            t.HasCheckConstraint("study_reminder_day_of_week_chk", "day_of_week between 1 and 7");
                        });

                    b.HasData(
                        new
                        {
                            StudyReminderId = 1,
                            Code = "MON",
                            DayOfWeek = 1,
                            Name = "Monday"
                        },
                        new
                        {
                            StudyReminderId = 2,
                            Code = "TUE",
                            DayOfWeek = 2,
                            Name = "Tuesday"
                        },
                        new
                        {
                            StudyReminderId = 3,
                            Code = "WED",
                            DayOfWeek = 3,
                            Name = "Wednesday"
                        },
                        new
                        {
                            StudyReminderId = 4,
                            Code = "THU",
                            DayOfWeek = 4,
                            Name = "Thursday"
                        },
                        new
                        {
                            StudyReminderId = 5,
                            Code = "FRI",
                            DayOfWeek = 5,
                            Name = "Friday"
                        },
                        new
                        {
                            StudyReminderId = 6,
                            Code = "SAT",
                            DayOfWeek = 6,
                            Name = "Saturday"
                        },
                        new
                        {
                            StudyReminderId = 7,
                            Code = "SUN",
                            DayOfWeek = 7,
                            Name = "Sunday"
                        });
                });

            modelBuilder.Entity("AlgoDuck.Models.Tag", b =>
                {
                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("tag_name");

                    b.HasKey("TagId")
                        .HasName("tag_pk");

                    b.ToTable("tag", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.TestCase", b =>
                {
                    b.Property<Guid>("TestCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_case_id");

                    b.Property<int>("ArrangeVariableCount")
                        .HasColumnType("integer")
                        .HasColumnName("arrange_variable_count");

                    b.Property<string>("CallFunc")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("call_func");

                    b.Property<string>("Display")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("display");

                    b.Property<string>("DisplayRes")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("display_res");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<bool>("OrderMatters")
                        .HasColumnType("boolean")
                        .HasColumnName("order_matters");

                    b.Property<Guid>("ProblemProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_problem_id");

                    b.HasKey("TestCaseId")
                        .HasName("test_case_pk");

                    b.HasIndex("ProblemProblemId");

                    b.ToTable("test_case", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.TestingResult", b =>
                {
                    b.Property<Guid>("TestCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_case_id");

                    b.Property<Guid>("CodeExecutionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_passed");

                    b.Property<Guid?>("UserSolutionSnapshotSnapShotId")
                        .HasColumnType("uuid");

                    b.HasKey("TestCaseId", "CodeExecutionId")
                        .HasName("PK_TestingResult");

                    b.HasIndex("CodeExecutionId");

                    b.HasIndex("UserSolutionSnapshotSnapShotId");

                    b.ToTable("testing_results", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.UserAchievement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("achievement_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_value");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_completed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("TargetValue")
                        .HasColumnType("integer")
                        .HasColumnName("target_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("user_achievement_pk");

                    b.HasIndex("IsCompleted")
                        .HasDatabaseName("user_achievement_is_completed_ix");

                    b.HasIndex("UserId")
                        .HasDatabaseName("user_achievement_user_id_ix");

                    b.HasIndex("UserId", "Code")
                        .IsUnique()
                        .HasDatabaseName("user_achievement_user_code_uq");

                    b.ToTable("user_achievement", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.UserConfig", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("EditorFontSize")
                        .HasColumnType("integer")
                        .HasColumnName("editor_font_size");

                    b.Property<Guid>("EditorThemeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EmailNotificationsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("email_notifications_enabled");

                    b.Property<bool>("IsDarkMode")
                        .HasColumnType("boolean")
                        .HasColumnName("is_dark_mode");

                    b.Property<bool>("IsHighContrast")
                        .HasColumnType("boolean")
                        .HasColumnName("is_high_contrast");

                    b.Property<DateTimeOffset?>("StudyReminderNextAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("study_reminder_next_at_utc");

                    b.HasKey("UserId")
                        .HasName("user_config_pk");

                    b.HasIndex("EditorThemeId");

                    b.ToTable("user_config", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.UserSetStudyReminder", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("StudyReminderId")
                        .HasColumnType("integer")
                        .HasColumnName("study_reminder_id");

                    b.Property<int?>("Hour")
                        .HasColumnType("integer")
                        .HasColumnName("hour");

                    b.HasKey("UserId", "StudyReminderId")
                        .HasName("user_set_reminder_pk");

                    b.HasIndex("StudyReminderId");

                    b.ToTable("user_set_reminder", null, t =>
                        {
                            t.HasCheckConstraint("user_set_reminder_hour_chk", "hour is null or (hour between 0 and 23)");
                        });
                });

            modelBuilder.Entity("AlgoDuck.Models.UserSolution", b =>
                {
                    b.Property<Guid>("SolutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("solution_id");

                    b.Property<long>("CodeRuntimeSubmitted")
                        .HasColumnType("bigint")
                        .HasColumnName("code_runtime_submitted");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<byte>("Stars")
                        .HasColumnType("smallint")
                        .HasColumnName("stars");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("SolutionId")
                        .HasName("user_solution_pk");

                    b.HasIndex("ProblemId");

                    b.HasIndex("UserId");

                    b.ToTable("user_solution", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.UserSolutionSnapshot", b =>
                {
                    b.Property<Guid>("SnapShotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_solution_snapshot_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("SnapShotId")
                        .HasName("user_solution_snapshot_id");

                    b.HasIndex("ProblemId");

                    b.HasIndex("UserId");

                    b.ToTable("user_solution_snapshots", (string)null);
                });

            modelBuilder.Entity("ContestProblem", b =>
                {
                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<Guid>("ContestId")
                        .HasColumnType("uuid")
                        .HasColumnName("contest_id");

                    b.HasKey("ProblemId", "ContestId")
                        .HasName("contest_problem_pk");

                    b.HasIndex("ContestId");

                    b.ToTable("contest_problem", (string)null);
                });

            modelBuilder.Entity("HasTag", b =>
                {
                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.HasKey("TagId", "ProblemId")
                        .HasName("has_tag_pk");

                    b.HasIndex("ProblemId");

                    b.ToTable("has_tag", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.DuckItem", b =>
                {
                    b.HasBaseType("AlgoDuck.Models.Item");

                    b.HasDiscriminator().HasValue("duck");
                });

            modelBuilder.Entity("AlgoDuck.Models.PlantItem", b =>
                {
                    b.HasBaseType("AlgoDuck.Models.Item");

                    b.Property<byte>("Height")
                        .HasColumnType("smallint")
                        .HasColumnName("plant_height");

                    b.Property<byte>("Width")
                        .HasColumnType("smallint")
                        .HasColumnName("plant_width");

                    b.HasDiscriminator().HasValue("plant");
                });

            modelBuilder.Entity("AlgoDuck.Models.DuckOwnership", b =>
                {
                    b.HasBaseType("AlgoDuck.Models.ItemOwnership");

                    b.Property<bool>("SelectedAsAvatar")
                        .HasColumnType("boolean")
                        .HasColumnName("duck_selected_as_avatar");

                    b.Property<bool>("SelectedForPond")
                        .HasColumnType("boolean")
                        .HasColumnName("duck_selected_for_pond");

                    b.HasDiscriminator().HasValue("duck");
                });

            modelBuilder.Entity("AlgoDuck.Models.PlantOwnership", b =>
                {
                    b.HasBaseType("AlgoDuck.Models.ItemOwnership");

                    b.Property<byte?>("GridX")
                        .HasColumnType("smallint")
                        .HasColumnName("plant_grid_x");

                    b.Property<byte?>("GridY")
                        .HasColumnType("smallint")
                        .HasColumnName("plant_grid_y");

                    b.HasDiscriminator().HasValue("plant");
                });

            modelBuilder.Entity("AlgoDuck.Models.ApiKey", b =>
                {
                    b.HasOne("AlgoDuck.Models.ApplicationUser", "User")
                        .WithMany("ApiKeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("api_key_application_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlgoDuck.Models.ApplicationUser", b =>
                {
                    b.HasOne("AlgoDuck.Models.Cohort", "Cohort")
                        .WithMany("ApplicationUsers")
                        .HasForeignKey("CohortId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("user_cohort_ref");

                    b.Navigation("Cohort");
                });

            modelBuilder.Entity("AlgoDuck.Models.AssistanceMessage", b =>
                {
                    b.HasOne("AlgoDuck.Models.AssistantChat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("AlgoDuck.Models.AssistantChat", b =>
                {
                    b.HasOne("AlgoDuck.Models.Problem", "Problem")
                        .WithMany("AssistantChats")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlgoDuck.Models.ApplicationUser", "User")
                        .WithMany("AssistantChats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Problem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlgoDuck.Models.AssistantMessageFragment", b =>
                {
                    b.HasOne("AlgoDuck.Models.AssistanceMessage", "Message")
                        .WithMany("Fragments")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("AlgoDuck.Models.CodeExecutionStatistics", b =>
                {
                    b.HasOne("AlgoDuck.Models.Problem", "Problem")
                        .WithMany("CodeExecutionStatistics")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AlgoDuck.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("CodeExecutionStatistics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("AlgoDuck.Models.Cohort", b =>
                {
                    b.HasOne("AlgoDuck.Models.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("AlgoDuck.Models.Contest", b =>
                {
                    b.HasOne("AlgoDuck.Models.Item", "Item")
                        .WithMany("Contests")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("contest_item_ref");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("AlgoDuck.Models.Item", b =>
                {
                    b.HasOne("AlgoDuck.Models.ApplicationUser", "CreatedBy")
                        .WithMany("CreatedItems")
                        .HasForeignKey("CreatedById");

                    b.HasOne("AlgoDuck.Models.Rarity", "Rarity")
                        .WithMany("Items")
                        .HasForeignKey("RarityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("item_rarity_ref");

                    b.Navigation("CreatedBy");

                    b.Navigation("Rarity");
                });

            modelBuilder.Entity("AlgoDuck.Models.ItemOwnership", b =>
                {
                    b.HasOne("AlgoDuck.Models.Item", "Item")
                        .WithMany("Purchases")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("item_purchase_ref");

                    b.HasOne("AlgoDuck.Models.ApplicationUser", "User")
                        .WithMany("Purchases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("purchase_user_ref");

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlgoDuck.Models.Message", b =>
                {
                    b.HasOne("AlgoDuck.Models.Cohort", "Cohort")
                        .WithMany("Messages")
                        .HasForeignKey("CohortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("message_cohort_ref");

                    b.HasOne("AlgoDuck.Models.ApplicationUser", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("message_user_ref");

                    b.Navigation("Cohort");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlgoDuck.Models.OwnsLayout", b =>
                {
                    b.HasOne("AlgoDuck.Models.EditorLayout", "Layout")
                        .WithMany("OwnedBy")
                        .HasForeignKey("LayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlgoDuck.Models.ApplicationUser", "User")
                        .WithMany("EditorLayouts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Layout");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlgoDuck.Models.Problem", b =>
                {
                    b.HasOne("AlgoDuck.Models.Category", "Category")
                        .WithMany("Problems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("problem_category_ref");

                    b.HasOne("AlgoDuck.Models.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlgoDuck.Models.Difficulty", "Difficulty")
                        .WithMany("Problems")
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("problem_difficulty_ref");

                    b.Navigation("Category");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Difficulty");
                });

            modelBuilder.Entity("AlgoDuck.Models.PurchasedTestCase", b =>
                {
                    b.HasOne("AlgoDuck.Models.TestCase", "TestCase")
                        .WithMany("PurchasedTestCases")
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlgoDuck.Models.ApplicationUser", "User")
                        .WithMany("PurchasedTestCases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestCase");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlgoDuck.Models.RefreshToken", b =>
                {
                    b.HasOne("AlgoDuck.Models.RefreshToken", "ReplacedByToken")
                        .WithMany("InverseReplacedByToken")
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("refresh_token_replaced_by_token");

                    b.HasOne("AlgoDuck.Models.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("refresh_token_session");

                    b.HasOne("AlgoDuck.Models.ApplicationUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("refresh_token_application_user");

                    b.Navigation("ReplacedByToken");

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlgoDuck.Models.Session", b =>
                {
                    b.HasOne("AlgoDuck.Models.Session", "ReplacedBySession")
                        .WithMany("InverseReplacedBySession")
                        .HasForeignKey("ReplacedBySessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("session_replaced_by_session");

                    b.HasOne("AlgoDuck.Models.ApplicationUser", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("session_application_user");

                    b.Navigation("ReplacedBySession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlgoDuck.Models.TestCase", b =>
                {
                    b.HasOne("AlgoDuck.Models.Problem", "ProblemProblem")
                        .WithMany("TestCases")
                        .HasForeignKey("ProblemProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("test_case_problem");

                    b.Navigation("ProblemProblem");
                });

            modelBuilder.Entity("AlgoDuck.Models.TestingResult", b =>
                {
                    b.HasOne("AlgoDuck.Models.CodeExecutionStatistics", "CodeExecution")
                        .WithMany("TestingResults")
                        .HasForeignKey("CodeExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlgoDuck.Models.TestCase", "TestCase")
                        .WithMany("TestingResults")
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlgoDuck.Models.UserSolutionSnapshot", null)
                        .WithMany("TestingSnapshotsResults")
                        .HasForeignKey("UserSolutionSnapshotSnapShotId");

                    b.Navigation("CodeExecution");

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("AlgoDuck.Models.UserAchievement", b =>
                {
                    b.HasOne("AlgoDuck.Models.ApplicationUser", "User")
                        .WithMany("UserAchievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_achievement_user_ref");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlgoDuck.Models.UserConfig", b =>
                {
                    b.HasOne("AlgoDuck.Models.EditorTheme", "EditorTheme")
                        .WithMany("UserConfigs")
                        .HasForeignKey("EditorThemeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AlgoDuck.Models.ApplicationUser", "User")
                        .WithOne("UserConfig")
                        .HasForeignKey("AlgoDuck.Models.UserConfig", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_config_application_user");

                    b.Navigation("EditorTheme");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlgoDuck.Models.UserSetStudyReminder", b =>
                {
                    b.HasOne("AlgoDuck.Models.StudyReminder", "StudyReminder")
                        .WithMany("UserSetStudyReminders")
                        .HasForeignKey("StudyReminderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_set_reminder_study_reminder_ref");

                    b.HasOne("AlgoDuck.Models.ApplicationUser", "User")
                        .WithMany("UserSetStudyReminders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_set_reminder_user_ref");

                    b.Navigation("StudyReminder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlgoDuck.Models.UserSolution", b =>
                {
                    b.HasOne("AlgoDuck.Models.Problem", "Problem")
                        .WithMany("UserSolutions")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_solution_problem_ref");

                    b.HasOne("AlgoDuck.Models.ApplicationUser", "User")
                        .WithMany("UserSolutions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("solution_user_ref");

                    b.Navigation("Problem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlgoDuck.Models.UserSolutionSnapshot", b =>
                {
                    b.HasOne("AlgoDuck.Models.Problem", "Problem")
                        .WithMany("UserSolutionSnapshots")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlgoDuck.Models.ApplicationUser", "User")
                        .WithMany("UserSolutionSnapshots")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Problem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ContestProblem", b =>
                {
                    b.HasOne("AlgoDuck.Models.Contest", null)
                        .WithMany()
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("contest_problem_contest_ref");

                    b.HasOne("AlgoDuck.Models.Problem", null)
                        .WithMany()
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("contest_problem_problem_ref");
                });

            modelBuilder.Entity("HasTag", b =>
                {
                    b.HasOne("AlgoDuck.Models.Problem", null)
                        .WithMany()
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("has_tag_problem_ref");

                    b.HasOne("AlgoDuck.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("has_tag_tag_ref");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("AlgoDuck.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("AlgoDuck.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlgoDuck.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("AlgoDuck.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlgoDuck.Models.ApplicationUser", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("AssistantChats");

                    b.Navigation("CodeExecutionStatistics");

                    b.Navigation("CreatedItems");

                    b.Navigation("EditorLayouts");

                    b.Navigation("Messages");

                    b.Navigation("PurchasedTestCases");

                    b.Navigation("Purchases");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Sessions");

                    b.Navigation("UserAchievements");

                    b.Navigation("UserConfig");

                    b.Navigation("UserSetStudyReminders");

                    b.Navigation("UserSolutionSnapshots");

                    b.Navigation("UserSolutions");
                });

            modelBuilder.Entity("AlgoDuck.Models.AssistanceMessage", b =>
                {
                    b.Navigation("Fragments");
                });

            modelBuilder.Entity("AlgoDuck.Models.AssistantChat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("AlgoDuck.Models.Category", b =>
                {
                    b.Navigation("Problems");
                });

            modelBuilder.Entity("AlgoDuck.Models.CodeExecutionStatistics", b =>
                {
                    b.Navigation("TestingResults");
                });

            modelBuilder.Entity("AlgoDuck.Models.Cohort", b =>
                {
                    b.Navigation("ApplicationUsers");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("AlgoDuck.Models.Difficulty", b =>
                {
                    b.Navigation("Problems");
                });

            modelBuilder.Entity("AlgoDuck.Models.EditorLayout", b =>
                {
                    b.Navigation("OwnedBy");
                });

            modelBuilder.Entity("AlgoDuck.Models.EditorTheme", b =>
                {
                    b.Navigation("UserConfigs");
                });

            modelBuilder.Entity("AlgoDuck.Models.Item", b =>
                {
                    b.Navigation("Contests");

                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("AlgoDuck.Models.Problem", b =>
                {
                    b.Navigation("AssistantChats");

                    b.Navigation("CodeExecutionStatistics");

                    b.Navigation("TestCases");

                    b.Navigation("UserSolutionSnapshots");

                    b.Navigation("UserSolutions");
                });

            modelBuilder.Entity("AlgoDuck.Models.Rarity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("AlgoDuck.Models.RefreshToken", b =>
                {
                    b.Navigation("InverseReplacedByToken");
                });

            modelBuilder.Entity("AlgoDuck.Models.Session", b =>
                {
                    b.Navigation("InverseReplacedBySession");
                });

            modelBuilder.Entity("AlgoDuck.Models.StudyReminder", b =>
                {
                    b.Navigation("UserSetStudyReminders");
                });

            modelBuilder.Entity("AlgoDuck.Models.TestCase", b =>
                {
                    b.Navigation("PurchasedTestCases");

                    b.Navigation("TestingResults");
                });

            modelBuilder.Entity("AlgoDuck.Models.UserSolutionSnapshot", b =>
                {
                    b.Navigation("TestingSnapshotsResults");
                });
#pragma warning restore 612, 618
        }
    }
}
